import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/global.css';
import Navbar from '@/components/Navbar';
import { cn } from '@/utils';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'max-w-full md:max-w-xl lg:max-w-4xl xl:max-w-7xl mx-auto')}>
        <Navbar />
        <div className="mt-5">{children}</div>
      </body>
    </html>
  );
}
